### ISSUE TITLE
Information for hardware and software requirements

### ISSUE THREAD

**Issue by DragonbornSoulI** [dockminer/gminer#4]
Mising information for hardware and software requirements in readme file or on site of Gminer. Which ports and ip ranges should be open for proper work of Gminer? Miners need them to know which of them to be allowed. Some miners have issues because of blocked ports and ip's for developer fee or something else. Security software blocks part of them and maybe all of them. List them in readme file or another visible place for good of miners.

**Comment by ZhaoTzuHsien** [comment]
Since this is a community maintained Docker image, everything specific to GMiner isn't our goal of the project (including hardware requirement and developer fee, etc). This is because those information is maintained by GMiner and we can't control on impact anything about that. Our project is simply a Docker wraper of GMiner release. For more information, you should head on to GMiner's offical page or their GitHub release page.
